"""
Author: Ben Janis
Date: 2025

This source file is part of an example system for MITRE's 2025 Embedded System CTF
(eCTF). This code is being provided only for educational purposes for the 2025 MITRE
eCTF competition, and may not meet MITRE standards for quality. Use this code at your
own risk!

Copyright: Copyright (c) 2025 The MITRE Corporation
"""

import argparse
import json
from pathlib import Path
import struct
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.padding import _byte_padding_pad


from loguru import logger


def gen_subscription(
    secrets: bytes, device_id: int, start: int, end: int, channel: int
) -> bytes:
    """Generate the contents of a subscription.

    The output of this will be passed to the Decoder using ectf25.tv.subscribe

    :param secrets: Contents of the secrets file generated by ectf25_design.gen_secrets
    :param device_id: Device ID of the Decoder
    :param start: First timestamp the subscription is valid for
    :param end: Last timestamp the subscription is valid for
    :param channel: Channel to enable
    """
    # TODO: Update this function to provide a Decoder with whatever data it needs to
    #   subscribe to a new channel
    # Lance's Note: This will likely consist of just encrypting things like we do in other cases...

    # Load the json of the secrets file
    secrets = secrets.splitlines()[2][3:] # get the third line and shave off the comment
    secrets = json.loads(secrets)
    aes_key = bytes.fromhex(str(secrets["aes_key"]))
    aesgcm = AESGCM(aes_key)

    iv = bytes.fromhex(str("ABABABABABABABABABABABAB"))#  os.urandom(12)

    data = struct.pack("<IQQIQ", device_id, start, end, channel, 0) # i is 4 bits, Q is 8 bits
    print(len(data))
    # print(data.hex())

    cipher_text = aesgcm.encrypt(iv, data, None)
    # print(len(cipher_text) % 16)
    # cipher_text += b'\x08'*(len(cipher_text) % 16)
    print("CIPHER TEXT", cipher_text)
    print(len(cipher_text))
    print("CIPHER TEXT", cipher_text.hex())
    print("CIPHER TEXT", len(cipher_text.hex()))

    plaintext = aesgcm.decrypt(iv, cipher_text, None)
    print(plaintext)
    print("plain TEXT", plaintext.hex())
    print(len(data))

    # Pack the subscription. This will be sent to the decoder with ectf25.tv.subscribe
    return cipher_text


def parse_args():
    """Define and parse the command line arguments

    NOTE: Your design must not change this function
    """
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--force",
        "-f",
        action="store_true",
        help="Force creation of subscription file, overwriting existing file",
    )
    parser.add_argument(
        "secrets_file",
        type=argparse.FileType("rb"),
        help="Path to the secrets file created by ectf25_design.gen_secrets",
    )
    parser.add_argument("subscription_file", type=Path, help="Subscription output")
    parser.add_argument(
        "device_id", type=lambda x: int(x, 0), help="Device ID of the update recipient."
    )
    parser.add_argument(
        "start", type=lambda x: int(x, 0), help="Subscription start timestamp"
    )
    parser.add_argument("end", type=int, help="Subscription end timestamp")
    parser.add_argument("channel", type=int, help="Channel to subscribe to")
    return parser.parse_args()


def main():
    """Main function of gen_subscription

    You will likely not have to change this function
    """
    # Parse the command line arguments
    args = parse_args()

    subscription = gen_subscription(
        args.secrets_file.read(), args.device_id, args.start, args.end, args.channel
    )

    # Print the generated subscription for your own debugging
    # Attackers will NOT have access to the output of this (although they may have
    # subscriptions in certain scenarios), but feel free to remove
    #
    # NOTE: Printing sensitive data is generally not good security practice
    logger.debug(f"Generated subscription: {subscription}")

    # Open the file, erroring if the file exists unless the --force arg is provided
    with open(args.subscription_file, "wb" if args.force else "xb") as f:
        f.write(subscription)

    # For your own debugging. Feel free to remove
    logger.success(f"Wrote subscription to {str(args.subscription_file.absolute())}")


if __name__ == "__main__":
    main()
